Prototype user inventory
sethbonnie/smoothie-buddy pull request #3
Opened 2024-04-06 05:02 UTC by Airboy98

initial prototype for user inventory screen with hardcoded values in the table and dummy buttons for submitting the form, no trash can button in the delete column for each table record

eventually to be merged with main along with other prototypes

2024-04-06 14:28 UTC, brendanhuddleston18 reviewed
I noticed that your proto runs off of the App.js file.  This could cause conflicts when trying to merge other files that might be using App.js as well.  If we continue on this right we could also run into a 1000+ line App.js file with it doing multiple jobs compared to compartmentalizing our compenents and making them slick.

2024-04-09 05:34 UTC, sethbonnie requested changes
Instead of having all the prototype changes in the `./frontend` directory, they really should be in a `./prototypes/user-inventory/` directory.

We should reserve the `frontend` directory for the actual final app that we'll build.

2024-04-14 22:20 UTC, atinuke312 reviewed
I pulled the branched and ran it. It looks great and works perfectly fine on my end.

2024-04-14 23:14 UTC, sethbonnie approved these changes

2024-04-14 23:14 UTC, merged