Frontend my kitchen
sethbonnie/smoothie-buddy pull request #8
Opened 2024-04-16 19:40 UTC by Airboy98

created frontend/src/components and frontend/src/pages/ folders and transplanted and modified (detailed below) user-inventory prototype code to frontend/src/pages/Kitchen.js file and embedded the page component in frontend/src/App.js 

touched up a few bits of the My Kitchen table:
1. switched CSS color theme (a little closer to the overall red/yellow smoothie color theme we like, still needs workshopping)
2. decoupled the InputNumber components in the Quantity and Servings columns of the DataTable component
3. changed the step of InputNumber component in DataTable component Servings column to step by 1 instead of .25
4. created deleteHandler function that's currently used as a dummy trash icon delete button template in the delete column of DataTable and modified its CSS styling

2024-04-18 12:16 UTC, sethbonnie requested changes

2024-04-18 12:16 UTC, sethbonnie commented on frontend/src/pages/Kitchen.js
> +        inputClassName="quantity-input" // Apply custom class for input field
These comments are just restating what the code says, can you remove?

2024-04-18 12:16 UTC, sethbonnie commented on frontend/src/pages/Kitchen.js
> +  //--------------FUNCTION FOR TABLE SERVINGS TEMPLATE--------------
What's the purpose of these headers? Can they be removed?

2024-04-18 12:16 UTC, sethbonnie commented on frontend/src/pages/Kitchen.js
> +  //--------------STATIC ARRAY OF HARDCODED DATA FOR TABLE (eventually transplant to .json file)--------------
Probably can remove this

2024-04-18 12:16 UTC, sethbonnie commented on frontend/src/pages/Kitchen.js
> +                // optionGroupTemplate={groupedItemTemplate}
Can you remove unused code like this? It adds visual clutter while doing nothing.

2024-04-18 12:16 UTC, sethbonnie commented on frontend/src/pages/Kitchen.js
> +                //--------------INPUT FIELD FOR ITEM QUANTITY--------------
Same here, these unused lines should be removed.

2024-04-18 16:54 UTC, sethbonnie submitted a review, later dismissed

2024-04-19 02:04 UTC, nikitakabir approved these changes

2024-04-19 02:05 UTC, merged